###
# Run all examples:
# go run ./cmd --dir-path ./examples
#
# Or split by type:
# go run ./cmd \
#   --dir-path ./examples/rest \
#   --dir-path ./examples/graphql \
#   --dir-path ./examples/grpc \
#   --dir-path ./examples/kafka \
#   --dir-path ./examples/nats \
#   --dir-path ./examples/rabbitmq \
#   --dir-path ./examples/mqtt \
#   --dir-path ./examples/websocket \
#   --dir-path ./examples/s3 \
#   --dir-path ./examples/sqs \
#   --dir-path ./examples/sns \
#   --dir-path ./examples/pubsub \
#   --dir-path ./examples/azure-servicebus \
#   --dir-path ./examples/soap

###
GET {{host}}internal/v1/scenarios
Accept: application/json

###
GET {{host}}control-ui/users
Accept: application/json

###
POST {{host}}graphql
Content-Type: application/json

{
  "operationName": "GetHero",
  "query": "query GetHero($episode: String!) { hero(episode: $episode) { id name } }",
  "variables": {
    "episode": "NEWHOPE"
  }
}

###
GET {{host}}internal/kafka/dry-run/message-1
Accept: application/json

###
GET {{host}}internal/kafka/docker/message-1
Accept: application/json

###
GET {{host}}internal/queue/message-1
Accept: application/json

###
POST {{host}}internal/nats/dry-run/orders/order-1
Content-Type: application/json

{
  "orderId": "order-1"
}

###
POST {{host}}internal/nats/orders/order-1
Content-Type: application/json

{
  "orderId": "order-1"
}

###
POST {{host}}internal/rabbitmq/dry-run/payments/payment-1
Content-Type: application/json

{
  "paymentId": "payment-1"
}

###
POST {{host}}internal/rabbitmq/payments/payment-1
Content-Type: application/json

{
  "paymentId": "payment-1"
}

###
POST {{host}}internal/mqtt/dry-run/devices/device-1/telemetry
Content-Type: application/json

{
  "deviceId": "device-1"
}

###
POST {{host}}internal/mqtt/devices/device-1/telemetry
Content-Type: application/json

{
  "deviceId": "device-1"
}

###
GET {{host}}ws/dry-run/chat
Accept: application/json

###
PUT {{host}}s3/demo-bucket/readme.txt
Content-Type: text/plain

hello from gigamock

###
GET {{host}}s3/demo-bucket/readme.txt
Accept: text/plain

###
POST {{host}}aws/sqs/orders
Content-Type: application/json

{"orderId":"order-1"}

###
GET {{host}}aws/sqs/orders
Accept: application/json

###
POST {{host}}aws/sns/order-events
Content-Type: application/json

{"orderId":"order-1"}

###
GET {{host}}aws/sns/order-events
Accept: application/json

###
POST {{host}}gcp/pubsub/order-events/publish
Content-Type: application/json

{"orderId":"order-1"}

###
POST {{host}}gcp/pubsub/orders-sub/pull
Accept: application/json

###
POST {{host}}azure/servicebus/orders/send
Content-Type: application/json

{"orderId":"order-1"}

###
POST {{host}}azure/servicebus/orders/receive
Accept: application/json

###
POST {{host}}soap/customers
Content-Type: text/xml; charset=utf-8
SOAPAction: "GetCustomer"

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetCustomerRequest xmlns="urn:gigamock:customers">
      <customerId>customer-1</customerId>
    </GetCustomerRequest>
  </soap:Body>
</soap:Envelope>

###
