###
# Run:
# go run ./cmd --dir-path ./examples/rest --dir-path ./examples/starwars

###

GET {{host}}control-ui/users
Accept: application/json

###

GET {{host}}users
Accept: application/json

###

DELETE {{host}}users/1
Content-Type: application/json

{}

###
PUT {{host}}users/1
Content-Type: application/json

{}

###
##
## GET users list
##
GET {{host}}users
Accept: application/json
###

POST {{host}}users/1
Content-Type: application/json

{}

###

GET {{host}}starwars/heroes
Accept: application/json

###

GET {{host}}starwars/heroes/1
Accept: application/json

###
